<?php
/**
 * Class to handle the integration with WooCommerce Subscriptions.
 *
 * @package Qliro_One_For_WooCommerce/Classes
 */

defined( 'ABSPATH' ) || exit;

/**
 * Class Qliro_One_Subscriptions
 */
class Qliro_One_Subscriptions {
	public const GATEWAY_ID = 'qliro_one';

	/**
	 * Class constructor.
	 *
	 * @return void
	 */
	public function __construct() {
		add_action( 'woocommerce_scheduled_subscription_payment_qliro_one', array( $this, 'process_scheduled_payment' ), 10, 2 );

		// On successful payment method change, the customer is redirected back to the subscription view page. We need to handle the redirect and create a recurring token.
		add_action( 'woocommerce_account_view-subscription_endpoint', array( $this, 'handle_redirect_from_change_payment_method' ) );

		add_action( 'woocommerce_receipt_' . self::GATEWAY_ID, array( __CLASS__, 'display_add_card_on_receipt_page' ) );
	}

	/**
	 * Display the add card snippet on the receipt page after changing payment method for a subscription.
	 *
	 * @param int $order_id The order ID.
	 * @return void
	 */
	public static function display_add_card_on_receipt_page( $order_id ) {
		if ( ! is_wc_endpoint_url( 'order-pay' ) || ! isset( $_GET['qliro_redirect'] ) ) {
			return;
		}

		$subscription = wc_get_order( $order_id );
		if ( empty( $subscription ) ) {
			return;
		}

		$request  = new Qliro_One_Request_Save_Credit_Card( array( 'order_id' => $order_id ) );
		$response = $request->request();
		if ( is_wp_error( $response ) ) {
			return;
		}
		$html_snippet = $response['OrderForRegistrationTokenHtmlSnippet'];
		echo $html_snippet; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- This is a HTML snippet that is generated by Qliro and needs to be outputted as is.
	}

	public static function add_card_on_receipt_page_assets() {
		if ( ! is_wc_endpoint_url( 'order-pay' ) || ! isset( $_GET['qliro_redirect'] ) ) {
			return;
		}

		$src          = QLIRO_WC_PLUGIN_URL . '/assets/js/qliro-one-add-card.js';
		$dependencies = array();
		wp_enqueue_script( 'qliro-one-add-card', $src, $dependencies, QLIRO_WC_VERSION, false );
	}

	/**
	 * Builds the redirect URL to the receipt/payment page used adding a payment card from.
	 *
	 * @param WC_Order $order WooCommerce order instance used to generate the checkout payment URL.
	 * @return string Relative URL to the checkout payment page with the Qliro subscription redirect flag.
	 */
	public static function get_add_card_page_url( $order ) {
		// Note: since wp_safe_redirect is internally called by WC, we can only use a relative URL.
		return add_query_arg(
			array(
				'qliro_redirect' => 'subscription',
			),
			$order->get_checkout_payment_url()
		);
	}

	/**
	 * Builds the redirect URL to the confirmation page used to confirm a card change for a subscription.
	 *
	 * @param WC_Subscription $subscription WooCommerce subscription instance used to generate the confirmation URL.
	 * @return string Fully-qualified URL with the Qliro subscription redirect flag.
	 */
	public static function get_add_card_confirmation_url( $subscription ) {
		// Note: this URL has to be fully-qualified since it is called by Qliro and not internally by WC, so we need to include the home_url to ensure the correct domain is used.
		return add_query_arg(
			array(
				'qliro_redirect' => 'subscription',
			),
			home_url( $subscription->get_view_order_url() )
		);
	}

	/**
	 * Process subscription renewal.
	 *
	 * @param float    $amount_to_charge The amount to charge for the renewal.
	 * @param WC_Order $order The WooCommerce order that will be created as a result of the renewal.
	 *
	 * @return void
	 */
	public function process_scheduled_payment( $amount_to_charge, $order ) {
		// Get the order and the subscription objects.
		$subscriptions = wcs_get_subscriptions_for_renewal_order( $order->get_id() );

		foreach ( $subscriptions as $subscription ) {
			// See if we have a token stored on the subscription.
			$token_ids = $subscription->get_payment_tokens();
			if ( empty( $token_ids ) ) {
				$this->process_recurring_invoice_payment( $order, $subscription );
			} else {
				$this->process_recurring_card_payment( $order, $subscription, $token_ids );
			}
		}
	}

	/**
	 * Process recurring invoice payment.
	 *
	 * @param WC_Order        $order The order object.
	 * @param WC_Subscription $subscription The subscription object.
	 *
	 * @return void
	 */
	private function process_recurring_invoice_payment( $order, $subscription ) {
		$result = QLIRO_WC()->api->create_merchant_payment( $order->get_id() );

		// If the result is a WP_Error, fail the payment.
		if ( is_wp_error( $result ) ) {
			$subscription->payment_failed();
			$subscription->save();
			return;
		}

		// Set the required order meta for the renewal order.
		$order->add_meta_data( '_qliro_payment_transaction_id', $result['PaymentTransactions'][0]['PaymentTransactionId'], true );
		$order->add_meta_data( '_qliro_one_order_id', $result['OrderId'], true );
		$order->add_meta_data( '_qliro_one_merchant_reference', $order->get_order_number(), true );
		$order->add_meta_data( 'qliro_one_payment_method_name', 'QLIRO_INVOICE', true );
		$order->add_meta_data( 'qliro_one_payment_method_subtype_code', 'INVOICE', true );
		$order->add_order_note(
			sprintf(
				/* translators: %s: Order ID */
				__( 'Qliro recurring payment for order %s was successful.', 'qliro-for-woocommerce' ),
				$order->get_id()
			)
		);
		$order->save();

		// If the result is not a WP_Error, complete the payment.
		$subscription->payment_complete( $result['OrderId'] );
	}

	/**
	 * Process recurring card payment.
	 *
	 * @param WC_Order        $order The order object.
	 * @param WC_Subscription $subscription The subscription object.
	 * @param int[]           $token_ids The payment token ids.
	 *
	 * @return void
	 */
	private function process_recurring_card_payment( $order, $subscription, $token_ids ) {
		// If there are multiple payment tokens, use the one thats default.
		foreach ( $token_ids as $token_id ) {
			$token = WC_Payment_Tokens::get( $token_id );

			if ( $token && $token->is_default() ) {
				break;
			}
		}

		if ( empty( $token ) ) {
			$message = __( 'The previously associated payment token for this subscription is no longer valid or available.', 'qliro-for-woocommerce' );

			$order->add_order_note( $message );
			$subscription->add_order_note( $message );
			$subscription->payment_failed_for_related_order();
			return;
		}

		$result = QLIRO_WC()->api->create_merchant_payment( $order->get_id(), $token->get_token() );

		// If the result is a WP_Error, fail the payment.
		if ( is_wp_error( $result ) ) {
			$message = sprintf(
				/* translators: %s: Error message from the Qliro API. */
				__( 'The recurring payment failed due to an error communicating with Qliro: %s', 'qliro-for-woocommerce' ),
				$result->get_error_message()
			);

			$order->add_order_note( $message );
			$subscription->add_order_note( $message );
			$subscription->payment_failed_for_related_order();
			return;
		}

		// Set the required order meta for the renewal order.
		$order->add_meta_data( '_qliro_payment_transaction_id', $result['PaymentTransactions'][0]['PaymentTransactionId'], true );
		$order->add_meta_data( '_qliro_one_order_id', $result['OrderId'], true );
		$order->add_meta_data( '_qliro_one_merchant_reference', $order->get_order_number(), true );
		$order->add_meta_data( 'qliro_one_payment_method_name', 'CREDITCARDS', true );
		$order->add_meta_data( 'qliro_one_payment_method_subtype_code', $token->get_card_type(), true );
		$order->add_order_note(
			sprintf(
				/* translators: %s: Order ID */
				__( 'Qliro recurring payment for order %s was successful.', 'qliro-for-woocommerce' ),
				$order->get_id()
			)
		);
		$order->save();

		// If the result is not a WP_Error, complete the payment.
		$subscription->payment_complete( $result['OrderId'] );
	}

		/**
		 * Handle the redirect from the change payment method page.
		 *
		 * @param int $subscription_id The subscription ID.
		 * @return void
		 */
	public function handle_redirect_from_change_payment_method( $subscription_id ) {
		// We use the 'qliro_redirect' query var to determine if we are redirected from Qliro after changing payment method, otherwise the customer is viewing a subscription.
		$qliro_redirect = filter_input( INPUT_GET, 'qliro_redirect', FILTER_SANITIZE_FULL_SPECIAL_CHARS );
		if ( 'subscription' !== $qliro_redirect ) {
			return;
		}

		$subscription = wc_get_order( $subscription_id );
		if ( self::GATEWAY_ID !== $subscription->get_payment_method() ) {
			return;
		}

		$response = QLIRO_WC()->api->get_qliro_one_order( $subscription->get_transaction_id() );
		if ( is_wp_error( $response ) ) {
			if ( function_exists( 'wc_print_notice' ) ) {
				// translators: Error message.
				wc_print_notice( sprintf( __( 'Failed to update payment method. Reason: %s', 'qliro-for-woocommerce' ), $response->get_error_message() ), 'error' );
			}
			return;
		}

		$customer_token = $response['data']['order']['customerToken'] ?? null;
		$this->save_customer_token( $subscription, $customer_token );
		// translators: New subscription token.
		$subscription->add_order_note( sprintf( __( 'The payment method was changed by the customer. New subscription token: %s', 'qliro-for-woocommerce' ), $customer_token ) );
	}

	/**
	 * Check if the cart or order is a subscription of any type.
	 *
	 * @param WC_Order|null $order The WooCommerce order if available.
	 *
	 * @return bool
	 */
	public static function is_subscription( $order ) {
		if ( empty( $order ) ) {
			return self::cart_has_subscription();
		}

		return class_exists( 'WC_Subscriptions_Order' ) && wcs_order_contains_subscription( $order, array( 'parent', 'resubscribe', 'switch', 'renewal' ) );
	}

	/**
	 * Check if a cart contains a subscription.
	 *
	 * @return bool
	 */
	public static function cart_has_subscription() {
		if ( ! is_checkout() ) {
			return false;
		}

		return ( class_exists( 'WC_Subscriptions_Cart' ) && WC_Subscriptions_Cart::cart_contains_subscription() ) ||
			( function_exists( 'wcs_cart_contains_renewal' ) && wcs_cart_contains_renewal() ) ||
			( function_exists( 'wcs_cart_contains_failed_renewal_order_payment' ) && wcs_cart_contains_failed_renewal_order_payment() ) ||
			( function_exists( 'wcs_cart_contains_resubscribe' ) && wcs_cart_contains_resubscribe() ) ||
			( function_exists( 'wcs_cart_contains_early_renewal' ) && wcs_cart_contains_early_renewal() ) ||
			( function_exists( 'wcs_cart_contains_switches' ) && wcs_cart_contains_switches() );
	}


	/**
	 * Check if the cart or order is a subscription of any type.
	 *
	 * @param WC_Order $order The WooCommerce order.
	 *
	 * @return bool
	 */
	public static function is_subscription_renewal( $order ) {
		if ( null !== $order && class_exists( 'WC_Subscriptions_Order' ) && wcs_order_contains_subscription( $order, array( 'resubscribe', 'switch', 'renewal' ) ) ) {
			return true;
		}

		return false;
	}
}
