<?php
/**
 * Class to handle the integration with WooCommerce Subscriptions.
 *
 * @package Qliro_One_For_WooCommerce/Classes
 */

defined( 'ABSPATH' ) || exit;

/**
 * Class Qliro_One_Subscriptions
 */
class Qliro_One_Subscriptions {
	public const GATEWAY_ID = 'qliro_one';

	/**
	 * Meta key holding the Qliro order id of an in-progress card registration.
	 *
	 * @var string
	 */
	public const SAVE_CARD_ORDER_ID_KEY = '_qliro_one_save_card_order_id';

	/**
	 * Meta key holding the merchant reference of an in-progress card registration.
	 *
	 * @var string
	 */
	public const SAVE_CARD_REFERENCE_KEY = '_qliro_one_save_card_merchant_reference';

	/**
	 * Meta key set while waiting for Qliro to push the registered card.
	 *
	 * @var string
	 */
	public const SAVE_CARD_PENDING_KEY = '_qliro_one_save_card_pending';

	/**
	 * Meta key holding the confirmation id of an in-progress card registration.
	 *
	 * The id is the shared secret included in the push URL Qliro delivers the card to, and is
	 * what makes the callback verifiable. Never expose it to the customer.
	 *
	 * @var string
	 */
	public const SAVE_CARD_CONFIRMATION_ID_KEY = '_qliro_one_save_card_confirmation_id';

	/**
	 * Class constructor.
	 *
	 * @return void
	 */
	public function __construct() {
		add_action( 'woocommerce_scheduled_subscription_payment_qliro_one', array( $this, 'process_scheduled_payment' ), 10, 2 );

		// On successful payment method change, the customer is redirected back to the subscription view page. We need to handle the redirect and create a recurring token.
		add_action( 'woocommerce_account_view-subscription_endpoint', array( $this, 'handle_redirect_from_change_payment_method' ), 5 );

		// WooCommerce Subscriptions renders its subscription receipt template on the order-pay endpoint, which is where we display the card form.
		add_action( 'woocommerce_receipt_' . self::GATEWAY_ID, array( __CLASS__, 'display_add_card_page' ) );
	}

	/**
	 * Whether the current request is the Qliro add card page for the given subscription.
	 *
	 * @param int $subscription_id The subscription ID the page is expected to belong to. Optional.
	 * @return bool
	 */
	public static function is_add_card_page( $subscription_id = 0 ) {
		if ( ! is_wc_endpoint_url( 'order-pay' ) ) {
			return false;
		}

		if ( 'subscription' !== filter_input( INPUT_GET, 'qliro_redirect', FILTER_SANITIZE_FULL_SPECIAL_CHARS ) ) {
			return false;
		}

		if ( empty( $subscription_id ) ) {
			return true;
		}

		return absint( get_query_var( 'order-pay' ) ) === absint( $subscription_id );
	}

	/**
	 * Display the Qliro card form on the add card page.
	 *
	 * @param int $order_id The subscription ID.
	 * @return void
	 */
	public static function display_add_card_page( $order_id ) {
		$subscription = self::get_add_card_subscription( $order_id );
		if ( empty( $subscription ) ) {
			return;
		}

		$snippet = self::create_card_registration( $subscription );
		if ( is_wp_error( $snippet ) ) {
			wc_print_notice(
				sprintf(
					/* translators: %s: Error message from the Qliro API. */
					esc_html__( 'Could not load the card form. Reason: %s', 'qliro-for-woocommerce' ),
					esc_html( $snippet->get_error_message() )
				),
				'error'
			);
			return;
		}

		echo $snippet; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- This is a HTML snippet that is generated by Qliro and needs to be outputted as is.
	}

	/**
	 * Get the subscription the current add card request belongs to, if the request is valid.
	 *
	 * @param int $subscription_id The subscription ID.
	 * @return WC_Subscription|null
	 */
	private static function get_add_card_subscription( $subscription_id ) {
		if ( ! self::is_add_card_page( $subscription_id ) || ! function_exists( 'wcs_get_subscription' ) ) {
			return null;
		}

		$subscription = wcs_get_subscription( $subscription_id );
		if ( empty( $subscription ) || self::GATEWAY_ID !== $subscription->get_payment_method() ) {
			return null;
		}

		if ( ! current_user_can( 'edit_shop_subscription_payment_method', $subscription->get_id() ) ) { // phpcs:ignore WordPress.WP.Capabilities.Unknown -- Registered by WooCommerce Subscriptions.
			return null;
		}

		return $subscription;
	}

	/**
	 * Register a new card with Qliro and return the card form to display to the customer.
	 *
	 * @param WC_Subscription $subscription The subscription to register a card for.
	 * @return string|WP_Error The HTML snippet, or a WP_Error if the request failed.
	 */
	public static function create_card_registration( $subscription ) {
		$request  = new Qliro_One_Request_Save_Credit_Card( array( 'order_id' => $subscription->get_id() ) );
		$response = $request->request();

		if ( is_wp_error( $response ) ) {
			return $response;
		}

		if ( empty( $response['OrderId'] ) || empty( $response['OrderForRegistrationTokenHtmlSnippet'] ) ) {
			return new WP_Error( 'qliro_missing_card_form', __( 'Qliro did not return a card form.', 'qliro-for-woocommerce' ) );
		}

		// The card is registered as a separate Qliro order. Store its id so the push callback can find this subscription.
		$subscription->update_meta_data( self::SAVE_CARD_ORDER_ID_KEY, $response['OrderId'] );
		$subscription->update_meta_data( self::SAVE_CARD_REFERENCE_KEY, $request->get_merchant_reference() );
		// Qliro order ids are short sequential integers, so the confirmation id is what proves the callback belongs to this registration.
		$subscription->update_meta_data( self::SAVE_CARD_CONFIRMATION_ID_KEY, $request->get_confirmation_id() );
		$subscription->update_meta_data( self::SAVE_CARD_PENDING_KEY, 'yes' );
		$subscription->save();

		return $response['OrderForRegistrationTokenHtmlSnippet'];
	}

	/**
	 * Builds the URL to the page the customer adds a payment card from.
	 *
	 * @param WC_Subscription $subscription WooCommerce subscription instance used to generate the checkout payment URL.
	 * @return string URL to the order-pay endpoint with the Qliro subscription redirect flag.
	 */
	public static function get_add_card_page_url( $subscription ) {
		// Passing true omits 'pay_for_order', which makes the order-pay endpoint render the receipt template instead of the pay form.
		return add_query_arg(
			array(
				'qliro_redirect' => 'subscription',
			),
			$subscription->get_checkout_payment_url( true )
		);
	}

	/**
	 * Builds the redirect URL to the confirmation page used to confirm a card change for a subscription.
	 *
	 * @param WC_Subscription $subscription WooCommerce subscription instance used to generate the confirmation URL.
	 * @return string Fully-qualified URL with the Qliro subscription redirect flag.
	 */
	public static function get_add_card_confirmation_url( $subscription ) {
		return add_query_arg(
			array(
				'qliro_redirect' => 'subscription',
			),
			self::absolutize_url( $subscription->get_view_order_url() )
		);
	}

	/**
	 * Ensure a URL sent to Qliro is fully-qualified.
	 *
	 * Qliro resolves a relative URL against its own domain, so a site that makes its
	 * URLs relative would send the customer to Qliro instead of back to the store.
	 *
	 * @param string $url The URL to absolutize.
	 * @return string
	 */
	public static function absolutize_url( $url ) {
		if ( 0 === strpos( $url, 'http' ) ) {
			return $url;
		}

		return untrailingslashit( home_url() ) . '/' . ltrim( $url, '/' );
	}

	/**
	 * Process subscription renewal.
	 *
	 * @param float    $amount_to_charge The amount to charge for the renewal.
	 * @param WC_Order $order The WooCommerce order that will be created as a result of the renewal.
	 *
	 * @return void
	 */
	public function process_scheduled_payment( $amount_to_charge, $order ) {
		// Get the order and the subscription objects.
		$subscriptions = wcs_get_subscriptions_for_renewal_order( $order->get_id() );

		foreach ( $subscriptions as $subscription ) {
			// See if we have a token stored on the subscription.
			$token_ids = $subscription->get_payment_tokens();
			if ( empty( $token_ids ) ) {
				$this->process_recurring_invoice_payment( $order, $subscription );
			} else {
				$this->process_recurring_card_payment( $order, $subscription, $token_ids );
			}
		}
	}

	/**
	 * Process recurring invoice payment.
	 *
	 * @param WC_Order        $order The order object.
	 * @param WC_Subscription $subscription The subscription object.
	 *
	 * @return void
	 */
	private function process_recurring_invoice_payment( $order, $subscription ) {
		$result = QLIRO_WC()->api->create_merchant_payment( $order->get_id() );

		// If the result is a WP_Error, fail the payment.
		if ( is_wp_error( $result ) ) {
			$subscription->payment_failed();
			$subscription->save();
			return;
		}

		// Set the required order meta for the renewal order.
		$order->add_meta_data( '_qliro_payment_transaction_id', $result['PaymentTransactions'][0]['PaymentTransactionId'], true );
		$order->add_meta_data( '_qliro_one_order_id', $result['OrderId'], true );
		$order->add_meta_data( '_qliro_one_merchant_reference', $order->get_order_number(), true );
		$order->add_meta_data( 'qliro_one_payment_method_name', 'QLIRO_INVOICE', true );
		$order->add_meta_data( 'qliro_one_payment_method_subtype_code', 'INVOICE', true );
		$order->add_order_note(
			sprintf(
				/* translators: %s: Order ID */
				__( 'Qliro recurring payment for order %s was successful.', 'qliro-for-woocommerce' ),
				$order->get_id()
			)
		);
		$order->save();

		// If the result is not a WP_Error, complete the payment.
		$subscription->payment_complete( $result['OrderId'] );
	}

	/**
	 * Process recurring card payment.
	 *
	 * @param WC_Order        $order The order object.
	 * @param WC_Subscription $subscription The subscription object.
	 * @param int[]           $token_ids The payment token ids.
	 *
	 * @return void
	 */
	private function process_recurring_card_payment( $order, $subscription, $token_ids ) {
		// If there are multiple payment tokens, use the one thats default.
		foreach ( $token_ids as $token_id ) {
			$token = WC_Payment_Tokens::get( $token_id );

			if ( $token && $token->is_default() ) {
				break;
			}
		}

		if ( empty( $token ) ) {
			$message = __( 'The previously associated payment token for this subscription is no longer valid or available.', 'qliro-for-woocommerce' );

			$order->add_order_note( $message );
			$subscription->add_order_note( $message );
			$subscription->payment_failed_for_related_order();
			return;
		}

		$result = QLIRO_WC()->api->create_merchant_payment( $order->get_id(), $token->get_token() );

		// If the result is a WP_Error, fail the payment.
		if ( is_wp_error( $result ) ) {
			$message = sprintf(
				/* translators: %s: Error message from the Qliro API. */
				__( 'The recurring payment failed due to an error communicating with Qliro: %s', 'qliro-for-woocommerce' ),
				$result->get_error_message()
			);

			$order->add_order_note( $message );
			$subscription->add_order_note( $message );
			$subscription->payment_failed_for_related_order();
			return;
		}

		// Set the required order meta for the renewal order.
		$order->add_meta_data( '_qliro_payment_transaction_id', $result['PaymentTransactions'][0]['PaymentTransactionId'], true );
		$order->add_meta_data( '_qliro_one_order_id', $result['OrderId'], true );
		$order->add_meta_data( '_qliro_one_merchant_reference', $order->get_order_number(), true );
		$order->add_meta_data( 'qliro_one_payment_method_name', 'CREDITCARDS', true );
		$order->add_meta_data( 'qliro_one_payment_method_subtype_code', $token->get_card_type(), true );
		$order->add_order_note(
			sprintf(
				/* translators: %s: Order ID */
				__( 'Qliro recurring payment for order %s was successful.', 'qliro-for-woocommerce' ),
				$order->get_id()
			)
		);
		$order->save();

		// If the result is not a WP_Error, complete the payment.
		$subscription->payment_complete( $result['OrderId'] );
	}

	/**
	 * Handle the redirect from Qliro after the customer added a card.
	 *
	 * The card itself is delivered asynchronously to the save card callback, so this only
	 * reports the outcome to the customer.
	 *
	 * @param int $subscription_id The subscription ID.
	 * @return void
	 */
	public function handle_redirect_from_change_payment_method( $subscription_id ) {
		// We use the 'qliro_redirect' query var to determine if we are redirected from Qliro after changing payment method, otherwise the customer is viewing a subscription.
		$qliro_redirect = filter_input( INPUT_GET, 'qliro_redirect', FILTER_SANITIZE_FULL_SPECIAL_CHARS );
		if ( 'subscription' !== $qliro_redirect || ! function_exists( 'wcs_get_subscription' ) ) {
			return;
		}

		$subscription = wcs_get_subscription( $subscription_id );
		if ( empty( $subscription ) || self::GATEWAY_ID !== $subscription->get_payment_method() ) {
			return;
		}

		$qliro_order_id = $subscription->get_meta( self::SAVE_CARD_ORDER_ID_KEY );
		if ( empty( $qliro_order_id ) ) {
			return;
		}

		// The callback beat us to it, and has already saved the card.
		if ( empty( $subscription->get_meta( self::SAVE_CARD_PENDING_KEY ) ) ) {
			wc_print_notice( __( 'Your new payment card has been saved, and will be used for upcoming renewals.', 'qliro-for-woocommerce' ), 'success' );
			return;
		}

		wc_print_notice( __( 'Your new payment card is being registered. It will be used for upcoming renewals as soon as Qliro has confirmed it.', 'qliro-for-woocommerce' ), 'notice' );
	}

	/**
	 * Save a card registered with Qliro as the payment token to use for a subscription.
	 *
	 * Replaces any token already set on the subscription, so renewals use the new card.
	 *
	 * @param WC_Subscription $subscription The subscription to save the card for.
	 * @param array           $card The card as pushed by Qliro.
	 * @return WC_Payment_Token_CC|WP_Error
	 */
	public static function save_card_to_subscription( $subscription, $card ) {
		if ( empty( $card['Id'] ) ) {
			return new WP_Error( 'qliro_missing_card_id', __( 'Qliro did not include a card id.', 'qliro-for-woocommerce' ) );
		}

		$customer_id = $subscription->get_customer_id();
		$token       = null;

		// Qliro may push the same card more than once, so reuse the token if we already have it.
		foreach ( WC_Payment_Tokens::get_customer_tokens( $customer_id, self::GATEWAY_ID ) as $existing_token ) {
			if ( $existing_token->get_token() === $card['Id'] ) {
				$token = $existing_token;
				break;
			}
		}

		if ( empty( $token ) ) {
			$token = new WC_Payment_Token_CC();
			$token->set_gateway_id( self::GATEWAY_ID );
			$token->set_token( $card['Id'] );
			$token->set_user_id( $customer_id );
			$token->set_last4( $card['CardLast4Digits'] ?? '' );
			// Pad the month to ensure its always 2 digits.
			$token->set_expiry_month( str_pad( $card['CardExpiryMonth'] ?? '', 2, '0', STR_PAD_LEFT ) );
			$token->set_expiry_year( $card['CardExpiryYear'] ?? '' );
			$token->set_card_type( strtolower( $card['CardBrandName'] ?? '' ) );
			$token->save();
		}

		// Renewals pick the default token, so the card the customer just added has to become it.
		WC_Payment_Tokens::set_users_default( $customer_id, $token->get_id() );

		// Replace rather than append, so a renewal can not fall back to the card that was just changed away from.
		$subscription->get_data_store()->update_payment_token_ids( $subscription, array( $token->get_id() ) );
		$subscription->delete_meta_data( self::SAVE_CARD_PENDING_KEY );
		$subscription->save();

		$subscription->add_order_note(
			sprintf(
				/* translators: 1: Card brand, 2: Last four digits of the card. */
				__( 'The payment card for this subscription was changed by the customer to %1$s ending in %2$s.', 'qliro-for-woocommerce' ),
				$token->get_card_type(),
				$token->get_last4()
			)
		);

		return $token;
	}

	/**
	 * Get the subscription an in-progress card registration belongs to.
	 *
	 * The confirmation id is the secret we put in the push URL, so finding a subscription by it is
	 * what ties an inbound callback to a registration we started.
	 *
	 * @param string $confirmation_id The confirmation id of the card registration.
	 * @return WC_Subscription|null
	 */
	public static function get_subscription_by_save_card_confirmation_id( $confirmation_id ) {
		if ( empty( $confirmation_id ) ) {
			return null;
		}

		$subscriptions = wc_get_orders(
			array(
				'type'         => 'shop_subscription',
				// Subscription statuses are not order statuses, which the query defaults to.
				'status'       => 'any',
				'limit'        => 1,
				'meta_key'     => self::SAVE_CARD_CONFIRMATION_ID_KEY, // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_key
				'meta_value'   => $confirmation_id, // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_value
				'meta_compare' => '=',
			)
		);

		$subscription = reset( $subscriptions );
		return empty( $subscription ) ? null : $subscription;
	}

	/**
	 * Check if the cart or order is a subscription of any type.
	 *
	 * @param WC_Order|null $order The WooCommerce order if available.
	 *
	 * @return bool
	 */
	public static function is_subscription( $order ) {
		if ( empty( $order ) ) {
			return self::cart_has_subscription();
		}

		return class_exists( 'WC_Subscriptions_Order' ) && wcs_order_contains_subscription( $order, array( 'parent', 'resubscribe', 'switch', 'renewal' ) );
	}

	/**
	 * Check if a cart contains a subscription.
	 *
	 * @return bool
	 */
	public static function cart_has_subscription() {
		if ( ! is_checkout() ) {
			return false;
		}

		return ( class_exists( 'WC_Subscriptions_Cart' ) && WC_Subscriptions_Cart::cart_contains_subscription() ) ||
			( function_exists( 'wcs_cart_contains_renewal' ) && wcs_cart_contains_renewal() ) ||
			( function_exists( 'wcs_cart_contains_failed_renewal_order_payment' ) && wcs_cart_contains_failed_renewal_order_payment() ) ||
			( function_exists( 'wcs_cart_contains_resubscribe' ) && wcs_cart_contains_resubscribe() ) ||
			( function_exists( 'wcs_cart_contains_early_renewal' ) && wcs_cart_contains_early_renewal() ) ||
			( function_exists( 'wcs_cart_contains_switches' ) && wcs_cart_contains_switches() );
	}


	/**
	 * Check if the cart or order is a subscription of any type.
	 *
	 * @param WC_Order $order The WooCommerce order.
	 *
	 * @return bool
	 */
	public static function is_subscription_renewal( $order ) {
		if ( null !== $order && class_exists( 'WC_Subscriptions_Order' ) && wcs_order_contains_subscription( $order, array( 'resubscribe', 'switch', 'renewal' ) ) ) {
			return true;
		}

		return false;
	}
}
