name: Create Dev Zip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Composer Install
      run: composer install

    - name: NPM install
      run: npm ci && npm run build

    - name: Create zip file
      run: zip -r qliro-one-for-woocommerce.zip . -x@.kernlignore

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: qliro-one-for-woocommerce-zip
        path: qliro-one-for-woocommerce.zip