name: Create Dev Zip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Composer Install
      run: composer install

    - name: NPM install
      run: npm ci && npm run build

    - name: Get branch name and commit hash
      id: vars
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
        COMMIT_HASH=$(git rev-parse --short HEAD)
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV

    - name: Create temporary directory
      run: mkdir -p temp/qliro-one-for-woocommerce

    - name: Copy files excluding .kernlignore patterns
      run: rsync -av --exclude-from='.kernlignore' --exclude='temp' . temp/qliro-one-for-woocommerce

    - name: Create zip file
      run: |
        cd temp
        zip -r ../qliro-one-for-woocommerce-${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}.zip qliro-one-for-woocommerce

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_KROKEDIL_PLUGIN_DEV_ZIP }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_KROKEDIL_PLUGIN_DEV_ZIP }}
        aws-region: eu-north-1

    - name: Upload to S3
      run: |
        aws s3 cp qliro-one-for-woocommerce-${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}.zip s3://krokedil-plugin-dev-zip/qliro-one-for-woocommerce-${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}.zip --acl public-read

    - name: Output S3 URL
      run: echo "Download URL: https://krokedil-plugin-dev-zip.s3.amazonaws.com/qliro-one-for-woocommerce-${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}.zip"