name: Create Dev Zip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Composer Install
      run: composer install

    - name: NPM install
      run: npm ci && npm run build

    - name: Get branch name and commit hash
      id: vars
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
        COMMIT_HASH=$(git rev-parse --short HEAD)
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV

    - name: Create temporary directory
      run: mkdir -p temp/qliro-one-for-woocommerce

    - name: Debug .kernlignore file
      run: cat .kernlignore

    - name: Copy files excluding .kernlignore patterns
      run: rsync -av --exclude-from='.kernlignore' --exclude='temp' . temp/qliro-one-for-woocommerce

    - name: List files in temp directory
      run: ls -R temp/qliro-one-for-woocommerce

    - name: Create zip file
      run: |
        cd temp/qliro-one-for-woocommerce
        zip -r ../../qliro-one-for-woocommerce-${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: qliro-one-for-woocommerce-${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}
        path: qliro-one-for-woocommerce-${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}.zip